#!/bin/bash

# file to properly compile tuningFork.c using gcc
# Warning: do not change the name of tuningFork.c
# Should compile under both Mac and Linux

returnStatus=$(gcc -o tf tuningFork.c)
exit $returnStatus
