#!/bin/bash

# file to properly compile tuningFork.c using gcc
# Warning: do not change the name of tuningFork.c
# Should compile under both Mac and Linux

gcc -fopenmp -o tf -Wall tuningFork.c -lm # echo to stdout or stderr
# includes -lm to link to math library
exit $? # status of gcc
