#!/bin/bash

# A shell script to interface with tuningFork.c

if [[ ! -f tf ]]; then # create the executable file
	if [[ ! gcc -o tf tuningFork.c ]]; then # failed compilation
		echo "Compilation of tuningFork.c failed"
		echo "Exiting with status (1)"
		exit 1
	fi
fi

# ./tf executable should exist

# rest is left to implement

exit 0
